global using System;
global using System.Text;
global using System.Runtime.InteropServices;
global using System.Collections.Generic;
global using System.Collections;
global using System.IO;
global using System.Linq;
global using SunamoIni._sunamo.SunamoExceptions;
global using System.Diagnostics;
global using System.Reflection;
global using System.Net;
global using System.Diagnostics.CodeAnalysis;
global using SunamoIni;
global using SunamoIni._sunamo;
global using SharpConfig;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
